TravelServiceAssignment_Consumer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelServiceAssignment_Consumer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TravelServiceAssignment_Consumer/Controllers/OrderTourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelServiceAssignment_Consumer.TravelService;

namespace TravelServiceAssignment_Consumer.Controllers
{
    public class OrderTourController : Controller
    {
        TravelServiceClient tsc = new TravelServiceClient();
        // GET: OrderTour
        public ActionResult Index()
        {
            return View();
        }

        // GET: OrderTour/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Failed()
        {
            return View();
        }

        // POST: OrderTour/Create
        [HttpPost]
        public ActionResult Create()
        {
            OrderTour ot = new OrderTour();

            ot.CustomerEmail = HttpContext.Request.Form["CustomerEmail"];
            ot.CustomerName = HttpContext.Request.Form["CustomerName"];
            ot.CustomerPhoneNumber = HttpContext.Request.Form["CustomerPhoneNumber"];
            ot.DayDuration = int.Parse(HttpContext.Request.Form["DayDuration"]);
            ot.PeopleAmount = int.Parse(HttpContext.Request.Form["PeopleAmount"]);
            ot.TourId = int.Parse(HttpContext.Request.Form["TourId"]);

            bool status = tsc.AddOrderTour(ot);

            if (status)
            {
                return RedirectToAction("Success", "OrderTour");
            }
            else
            {
                return RedirectToAction("Failed", "OrderTour");
            }
        }

        // GET: OrderTour/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderTour/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderTour/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderTour/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TravelServiceAssignment_Consumer/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelServiceAssignment_Consumer.TravelService;

namespace TravelServiceAssignment_Consumer.Controllers
{
    public class TourController : Controller
    {
        TravelServiceClient tsc = new TravelServiceClient();
        // GET: Tour
        public ActionResult Index()
        {
            ViewBag.listTours = tsc.GetTourList();
            return View();
        }

        // GET: Tour/Details/5
        public ActionResult Details(int id)
        {
            var tour = tsc.GetTourById(id);
            return View(tour);
        }

        // POST: Tour/Create
        [HttpPost]
        public ActionResult Create(OrderTour ot)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tour/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Tour/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tour/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Tour/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TravelServiceAssignment_Consumer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TravelServiceAssignment_Consumer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TravelServiceAssignment_Consumer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "EAST 2 WEST TRAVEL SERVICE";
}

<div class="jumbotron">
    <h1>EAST 2 WEST TRAVEL SERVICE.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>


<p>@Html.ActionLink("There is Our Tours List for You to Choose!", "Index", "Tour");</p>

TravelServiceAssignment_Consumer/Views/OrderTour/Failed.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Failed</title>
</head>
<body>
    <h2>Order Tour Failed</h2>
</body>
</html>

TravelServiceAssignment_Consumer/Views/OrderTour/Order.cshtml
@model TravelServiceAssignment_Consumer.TravelService.OrderTour

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Order Tour</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>OrderTour</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PeopleAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PeopleAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PeopleAmount, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DayDuration, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DayDuration, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DayDuration, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CustomerPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerPhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.TourId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TourId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TourId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

TravelServiceAssignment_Consumer/Views/OrderTour/StatusFailed.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StatusFailed</title>
</head>
<body>
    <h2>Order Tour Failed</h2>
</body>
</html>

TravelServiceAssignment_Consumer/Views/OrderTour/StatusSuccess.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StatusSuccess</title>
</head>
<body>
    <h2>Order Tour Success</h2>
</body>
</html>

TravelServiceAssignment_Consumer/Views/OrderTour/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <h2>Order Tour Success</h2>
</body>
</html>

TravelServiceAssignment_Consumer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TravelServiceAssignment_Consumer/Views/Tour/Details.cshtml
@model TravelServiceAssignment_Consumer.TravelService.Tour

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Order Tour</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body style="font-family: Constantia;">
    <div style="margin: 0 auto">
        <h2>Order Tour: @Html.DisplayFor(model => model.Name) - Place: @Html.DisplayFor(model => model.Place)</h2>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Place)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Place)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BasePrice)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BasePrice)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    </div>
    <input style="display: none" id="base-price" value="@Html.DisplayFor(model => model.BasePrice)"/>
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading"><h2>Please Fill your Information here!</h2></div>
            <div class="panel-body">
                <form class="form-horizontal" method="POST" action="/OrderTour/Create">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="name">Customer Name:</label>
                        <div class="col-sm-10">
                            <input required type="text" class="form-control" name="CustomerName" placeholder="Enter Your Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="customerPhoneNumber">Phone Number:</label>
                        <div class="col-sm-10">
                            <input required type="text" class="form-control" name="CustomerPhoneNumber" placeholder="Enter Your Phone Number">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="CustomerEmail">Customer Email:</label>
                        <div class="col-sm-10">
                            <input required type="text" class="form-control" name="CustomerEmail" placeholder="Enter Your Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="PeopleAmount">People Amount:</label>
                        <div class="col-sm-10">
                            <input required type="number" onblur="getTotalCost()" class="form-control" id="people-amount" name="PeopleAmount" placeholder="Enter Your Total People">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="DayDuration">Days Duration:</label>
                        <div class="col-sm-10">
                            <input required type="number" onblur="getTotalCost()" class="form-control" id="day-duration" name="DayDuration" placeholder="Enter Your Days Duration">
                        </div>
                    </div>
                    <div class="form-group" style="display: none">
                        <label class="control-label col-sm-2" for="">Tour Id:</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" name="TourId" value="@Html.DisplayFor(model => model.TourId)">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <p>Total Cost: <span style="font-weight: bolder; color: darkred" id="total-cost"></span> VNĐ</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2" style="display: none">
                            <input type="number" class="form-control" id="total-cost-inp" name="TotalCost" value="">
                        </div>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-default">Order this Tour</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Back to Tour List", "Index")
    </p>
    <script>
        function getTotalCost() {
            var peopleAmount = parseInt(document.getElementById('people-amount').value);
            var dayDuration = parseInt(document.getElementById('day-duration').value);
            var basePrice = parseInt(document.getElementById('base-price').value);

            var totalCost = peopleAmount * dayDuration * basePrice * 1000;

            if (Number.isNaN(totalCost)) {
                document.getElementById('total-cost').innerHTML = numberWithCommas(totalCost);
                document.getElementById('total-cost-inp').value = totalCost;
            }
        }

        function numberWithCommas(x) {
            return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        }
    </script>
</body>
</html>

TravelServiceAssignment_Consumer/Views/Tour/Index.cshtml
@{
    Layout = null;
}
@using TravelServiceAssignment_Consumer.TravelService;

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>East To West Tour List</title>
</head>
<body style="font-family: Constantia; padding-top: 10%">
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading"><h1 style="text-align: center">Our Tours List</h1></div>
            <div class="panel-body">
                <table class="table table-condensed table-hover">
                    <tr style="font-weight: bolder">
                        <th>Tour Id</th>
                        <th>Name</th>
                        <th>Place </th>
                        <th>Base Price</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    @foreach (Tour t in ViewBag.listTours)
                    {
                        <tr>
                            <td>@t.TourId</td>
                            <td>@t.Name</td>
                            <td>@t.Place</td>
                            <td>@t.BasePrice</td>
                            <td>@t.Description</td>
                            <td>@Html.ActionLink("Order This Tour!", "Details", "Tour", new { id = t.TourId }, null)</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>
</html>